spring:
  datasource:
    url: jdbc:postgresql://db:5432/exchange
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      mode: never
server:
  port: 8080
logging:
  level:
    root: info