spring:
  datasource:
    url: jdbc:h2:mem:exchange
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: WARN

# Externalized API paths
api:
  base-path: /api
  calc-path: /calc
  history-path: /history
  status-path: /status
  rates-path: /rates

# Externalized cron expression
scheduling:
  currency-update-cron: "0 1 0 * * ?"

security:
  cors:
    allowed-origins:
      - http://localhost:4200
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE

